# Generated by Django 2.2.5 on 2019-09-27 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habilidades', '0001_initial'),
        ('categoria_heroi', '0001_initial'),
        ('universos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heroi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_heroi', to='categoria_heroi.Categoria')),
                ('habilidade', models.ManyToManyField(related_name='hab_heroi', to='habilidades.Habilidade')),
                ('universo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uni_heroi', to='universos.Universo')),
            ],
        ),
    ]
